#%RAML 1.0
title: Zero-OS Hub
version: 1.0
mediaType: application/json

securitySchemes:
  cookies:
    description: Cookie authentification
    type: Pass Through
    describedBy:
      headers:
        cookies:
          type: string

/repositories:
  get:
    description: List all repositories (users) found
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {"official": false, "name": "ahamdy"},
                {"official": false, "name": "azmy"},
                {"official": false, "name": "deboeckj"},
                {"official": true, "name": "dockers"},
                {"official": false, "name": "gig-autobuilder"},
                {"official": true, "name": "gig-official-apps"}
              ]

/flist:
  get:
    description: List all flist found, sorted alphabetically
    responses:
      200:
        body:
          application/json:
            example: |
              [
                "ahamdy/js9_ubuntu1.flist",
                "chaddad/js9f.flist",
                "gig-official-apps/ardb-forestdb.flist",
                "gig-official-apps/ardb-lmdb.flist",
                "xtremx/ubuntu_caddy.flist",
                "zaibon/flist.flist"
                ...
              ]

  /{username}:
    get:
      description: Get available flist for a specific user
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  {"updated": 1507149609, "type": "regular", "size": "84.41 KB", "name": "0-orchestrator-1.1.0-alpha-7.flist"},
                  {"updated": 1493109577, "type": "regular", "size": "9.79 KB", "name": "ardb-forestdb.flist"},
                  {"updated": 1507137785, "type": "regular", "size": "4.75 KB", "name": "ardb-lmdb.flist"},
                  {"updated": 1505824570, "type": "symlink", "size": "--", "name": "linked.flist", "target": "ardb-lmdb.flist"}
                  ...
                }
        404:
            description: User (repository) not found
 
  /{username}/{flist}:
    get:
      description: Get information about a specific flist
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  'content': [
                    {"path": "/var/lib/dpkg/alternatives/view", "size": 130},
                    {"path": "/var/lib/dpkg/triggers", "size": 0},
                    {"path": "/var/lib/dpkg/triggers/File", "size": 130},
                    {"path": "/var/lib/dpkg/triggers/resolvconf-enable-updates", "size": 130},
                    {"path": "/var/lib/dpkg/triggers/Lock", "size": 130},
                    {"path": "/var/lib/dpkg/triggers/ldconfig", "size": 130},
                    {"path": "/var/lib/dpkg/triggers/Unincorp", "size": 130},
                    {"path": "/var/lib/dpkg/triggers/update-initramfs", "size": 130},
                    ...
                  ],
                  'regular': 5,
                  'directory': 3,
                  'symlink': 4,
                  'special': 2
                }
        404:
          body:
            application/json:
              exemple: {"message": "source not found", "status": "error"}

  /me/upload:
    post:
      securedBy: [cookies]
      description: Upload a .tar.gz file and insert it to the hub
      cookies:
        caddyoauth:
          description: |
            ItsYouOnline JWT authentification. This JWT only needs to contains a valid username and expiration.
          required: true
        active-user:
          description: |
            Username to use during upload.
            This username needs to be set on the JWT as organization.
            Eg: to upload using 'hello' username, JWT needs to contains scope 'user:memberof:hello'
          required: false
      body:
        multipart/form-data:
          properties:
            file:
              description: The file to be uploaded
              required: true
              type: file
      responses:
        200:
          description: File renamed
        401:
          description: Not authentificated
        404:
          description: File not found

  /me/merge:
    post:
      securedBy: [cookies]
      description: Merge multiple flist together
      cookies:
        caddyoauth:
          description: |
            ItsYouOnline JWT authentification. This JWT only needs to contains a valid username and expiration.
          required: true
        active-user:
          description: |
            Username to use during upload.
            This username needs to be set on the JWT as organization.
            Eg: to upload using 'hello' username, JWT needs to contains scope 'user:memberof:hello'
          required: false
      responses:
        200:
          description: Files merged
        401:
          description: Not authentificated
        404:
          description: Flist not found

  /me/{flist}:
    delete:
      securedBy: [cookies]
      description: Delete one of your flist
      responses:
        200:
          description: File deleted
        401:
          description: Not authentificated
        404:
          description: File not found
    get:
      securedBy: [cookies]
      description: See '/flist/{user}/{flist}' GET endpoint
 
  /me/{flist}/rename/{target}:
    get:
      securedBy: [cookies]
      description: Rename one of your flist
      responses:
        200:
          description: File renamed
        401:
          description: Not authentificated
        404:
          description: Source file not found


  /me/{flist}/link/{linkname}:
    get:
      securedBy: [cookies]
      description: Create a flist link (symlink) updatable
      responses:
        200:
          description: Link created
        401:
          description: Not authentificated
        404:
          description: Source file not found

